### ISSUE TITLE
Calendar Function

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#24]
Need to find a calendar program.  Could be the same as what the auto-ISAC uses.  Then we should collect all the conferences from the calendar sources and put them into a single database.  This database should be used to show the conference calendar.

Additional Ideas
Webcrawlers to find new sources

**Comment by heldyboy** [comment]
Chris, can you see if you can start this?  The best way from my point of view is to take an existing calendar and copy / paste.... then we can add our own content.

**Comment by chrsengel** [comment]
Sure. I'll look for possible solutions.

**Comment by heldyboy** [comment]
Hey, can we discuss this one as well?

**Comment by chrsengel** [comment]
We could embed a public google calendar into the site. You only need to create one and make it public. Here's a [guide](https://support.google.com/calendar/answer/41207?hl=en).

Otherwise I don't know of any reliable solution for static pages. If we transition to a CMS like wordpress or build up our own infrastructure there will be more options.
