### ISSUE TITLE
Member Counter on the Main Page

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#30]
We should have a member counter on the main page to show the strength of the organization.  Somthing like this... 

<img width="1137" alt="Screen Shot 2019-12-10 at 06 42 18" src="https://user-images.githubusercontent.com/26025574/70498955-57894380-1b18-11ea-91bb-7b79a87550f7.png">

**Comment by chrsengel** [comment]
I'll look into that. We might be able to use the [meetup API](https://www.meetup.com/meetup_api/) to get the data directly. Looks like they allow cross origin requests.

**Comment by heldyboy** [comment]
Sounds good.  Thanks man.

**Comment by chrsengel** [comment]
Implemented in ae6198f5ef1fbfe7f2734164b21993a38d736797. Currently it only fetches members data for the locations listed in the [locations page](https://docs.asrg.io/locations), so if i.e. Munich is set up we can easily add them in the script.

I can't fetch the total number of past events because the API doesn't support this. So this (alongside the number of locations and the age) is hardcoded.

**Comment by heldyboy** [comment]
I have an idea... I think the best way to do this... is to use the Google Sheets API.  This way we can reference the number on the website to the google sheet with the members.  Then we can use the meetup API to update the google sheet.  

Membership Google Sheet:
https://drive.google.com/drive/u/1/folders/1bjoACBl16GZZYXQL6eNAC5U5gTtL55Fe

What do you think?

**Comment by heldyboy** [comment]
I think issue 41 will help with this one. 

https://github.com/ASRG/asrg.io/issues/41
