### ISSUE TITLE
Increase Security to reduce sign on attempts.

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#384]
![image](https://user-images.githubusercontent.com/26025574/141056755-2743f6fe-1992-4092-9e59-83f1e522e407.png)

**Comment by KellyDSD** [comment]
Hi - with regard to this one are these general wordpress notifications? Ok for me to assign myself using an email to keep watch? I will get these through Sucuri also but its best to have both.

**Comment by heldyboy** [comment]
These notifications are coming from the Limit Login Attempts Plugin.  

![image](https://user-images.githubusercontent.com/26025574/143246343-3a1c349e-dcc1-4adc-bf9c-da25c1ee059a.png)

**Comment by KellyDSD** [comment]
HI ok it is best we move this over to Wordfence to monitor as this will also throttle the requests from spam - if ok I will change this around 


Kelly   Lloyd
DUCK SOUP DIGITAL
Web Management | Development | Marketing | Managed Hosting                                          

***@***.***                                                                                                               

DUCKSOUPDIGITAL.CO.UK

                                                       

From: Heldy ***@***.***>
Reply: ASRG/asrg.io ***@***.***>
Date: 24 November 2021 at 13:24:26
To: ASRG/asrg.io ***@***.***>
Cc: KellyDSD ***@***.***>, Assign ***@***.***>
Subject:  Re: [ASRG/asrg.io] Increase Security to reduce sign on attempts. (Issue #384)  

These notifications are coming from the Limit Login Attempts Plugin.



—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heldyboy** [comment]
@KellyDSD Please go ahead with the changes.  Actually, are there any charges?

**Comment by KellyDSD** [comment]
Hi - do you mean to change over to Wordfence? No the free version for now should cover? Or do you mean implantation time? 


Kelly   Lloyd
DUCK SOUP DIGITAL
Web Management | Development | Marketing | Managed Hosting                                          

***@***.***                                                                                                               

DUCKSOUPDIGITAL.CO.UK

                                                       

From: Heldy ***@***.***>
Reply: ASRG/asrg.io ***@***.***>
Date: 24 November 2021 at 15:22:00
To: ASRG/asrg.io ***@***.***>
Cc: KellyDSD ***@***.***>, Mention ***@***.***>
Subject:  Re: [ASRG/asrg.io] Increase Security to reduce sign on attempts. (Issue #384)  

@KellyDSD Please go ahead with the changes. Actually, are there any charges?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heldyboy** [comment]
I meant software license costs.  If we can work with the free version, please go ahead and integrate.
