### ISSUE TITLE
Prabath will review the wordpress site and make recommendations. (Plugins, Development Environment, Style)

### ISSUE THREAD

**Issue by heldyboy** [ASRG/asrg.io#445]

**Comment by prabath-asrg** [comment]
I am still auditing the site. However, I have prepared a few documents:
[Rough Analysis of Pages](https://docs.google.com/spreadsheets/d/19GL7WLWcxAbHfsbqf9b3OVUipts9N5kFWSCnwoG3-QM/edit?usp=sharing)

[Site Map](https://internal-confluence.asrg.io/x/GoCzAQ)
[Personal Notes](https://internal-confluence.asrg.io/x/E4CzAQ) (This is only a personal note but will prepare a proper document after finishing the audit)

**Comment by heldyboy** [comment]
Please make sure that your review is finished until Thursday. Please also make sure that you bring an example of the landing page with your proposed design. And list of recommendations.

**Comment by prabath-asrg** [comment]
@heldyboy I am not sure whether I can design the landing page by Thursday for two reasons:

1. I have some comments on the branding guideline also so maybe upon discussing we can make some tweaks to it. Since the design of the page is dependent on the branding it's better to do it afterwards or I do the design with my suggestions.

2. Designing a landing page is a somewhat critical task that has to the user personas > user journies > wireframe > Low-fi design > Hi-fi design. Of course, I can show you something but it won't benefit you if we sacrifice quality over time. Hope you understand. 

Please let me know your thoughts regarding these two.

But for sure I will finish the review and list of recommendations.

**Comment by prabath-asrg** [comment]
@heldyboy @usman-asrg 
Here is the [Link to the Figma Design File](https://www.figma.com/file/17hjtOJTDv7rwyBOzikJSv/ASRG-Version-1?node-id=0%3A1)
